SET(TALIPOT_DIR ${CMAKE_INSTALL_PREFIX})
SET(TALIPOT_FOUND true)
SET(TALIPOT_INCLUDE_DIR ${TalipotCoreBuildInclude} ${TalipotCoreInclude} ${TalipotOGLInclude} ${TalipotOGDFInclude} ${TalipotGUIInclude} ${TalipotPythonInclude})
SET(TALIPOT_LIBRARIES ${LibTalipotCoreName} ${LibTalipotOglName} ${LibTalipotGUIName} ${LibTalipotOGDFName})

IF(WIN32)
  SET(TALIPOT_LIBRARIES_DIR ${TalipotBinInstallDir})
ELSE(WIN32)
  SET(TALIPOT_LIBRARIES_DIR ${TalipotLibInstallDir})
ENDIF(WIN32)
SET(TALIPOT_PLUGINS_DIR ${TalipotPluginsInstallDir})
SET(TALIPOT_GLYPH_PLUGINS_DIR ${TalipotGlyphPluginsInstallDir})
SET(TALIPOT_INTERACTOR_PLUGINS_DIR ${TalipotInteractorPluginsInstallDir})
SET(TALIPOT_VIEW_PLUGINS_DIR ${TalipotViewPluginsInstallDir})
SET(TALIPOT_PERSPECTIVE_PLUGINS_DIR ${TalipotPerspectivePluginsInstallDir})
SET(TALIPOT_CORE_LIBRARY ${LibTalipotCoreName})
SET(TALIPOT_OGL_LIBRARY ${LibTalipotOglName})
SET(TALIPOT_GUI_LIBRARY ${LibTalipotGUIName})
SET(TALIPOT_OGDF_LIBRARY ${LibTalipotOGDFName})
SET(TALIPOT_PYTHON_LIBRARY ${LibTalipotPythonName})
SET(TALIPOT_VERSION ${TalipotVersion})
SET(TALIPOT_MAJOR_VERSION ${TalipotMajorVersion})
SET(TALIPOT_MINOR_VERSION ${TalipotMinorVersion})
SET(TALIPOT_PATCH_VERSION ${TalipotReleaseVersion})
SET(TALIPOT_SHARE_DIR ${TalipotShareInstallDir})
SET(TALIPOT_USE_FILE ${CMAKE_SOURCE_DIR}/cmake/TalipotUseFile.cmake)
