/**
 *
 * Copyright (C) 2019  The Talipot developers
 *
 * Talipot is a fork of Tulip, created by David Auber
 * and the Tulip development Team from LaBRI, University of Bordeaux
 *
 * See the AUTHORS file at the top-level directory of this distribution
 * License: GNU General Public License version 3, or any later version
 * See top-level LICENSE file for more information
 *
 */

#ifndef CRASHHANDLING_H_
#define CRASHHANDLING_H_

#include <string>

#define TLP_PLATEFORM_HEADER "TLP_PLATEFORM"
#define TLP_ARCH_HEADER "TLP_ARCH"
#define TLP_COMPILER_HEADER "TLP_COMPILER"
#define TLP_VERSION_HEADER "TLP_VERSION"
#define TLP_DUMP_HEADER "TLP_DUMP"
#define TLP_STACK_BEGIN_HEADER "TLP_STACK_BEGIN"
#define TLP_STACK_END_HEADER "TLP_STACK_END"

class CrashHandling {

public:
  static void setDumpPath(std::string);

  static void installCrashHandler();

#ifdef _MSC_VER
  // function to add extra search paths for locating program databases (*.pdb files)
  // generated by Visual Studio.
  // Multiple paths can be provided, separated by a semi-colon (;).
  static void setExtraSymbolsSearchPaths(const std::string &searchPaths);
#endif
};

#endif /* CRASHHANDLING_H_ */
